import { userAvatars } from "./userAvatars";

export const mockUsers = [
  {
    id: 0,
    userName: "Alex King",
    role: "Leader",
    email: "alex.king@example.com",
    rank: "Legendary",
    avatar: userAvatars[0],
    totalWins: 100,
    winRate: 78,
    experience: 2450,
    currentStreak: 5,
    bestRank: 3,
  },
  {
    id: 1,
    userName: "Sarah Doe",
    role: "Co-Leader",
    email: "sarah.doe@example.com",
    rank: "Elite",
    avatar: userAvatars[1],
    totalWins: 85,
    winRate: 74,
    experience: 2100,
    currentStreak: 4,
    bestRank: 2,
  },
  {
    id: 2,
    userName: "Mike Doe",
    role: "Member",
    email: "mike.doe@example.com",
    rank: "Veteran",
    avatar: userAvatars[2],
    totalWins: 70,
    winRate: 68,
    experience: 1800,
    currentStreak: 3,
    bestRank: 6,
  },
  {
    id: 3,
    userName: "Alice Smith",
    role: "Member",
    email: "alice.smith@example.com",
    rank: "Rookie",
    avatar: userAvatars[3],
    totalWins: 30,
    winRate: 60,
    experience: 800,
    currentStreak: 1,
    bestRank: 10,
  },
  {
    id: 4,
    userName: "Bob Johnson",
    role: "Member",
    email: "bob.johnson@example.com",
    rank: "Novice",
    avatar: userAvatars[4],
    totalWins: 25,
    winRate: 55,
    experience: 600,
    currentStreak: 0,
    bestRank: 12,
  },
  {
    id: 5,
    userName: "Charlie Brown",
    role: "Member",
    email: "charlie.brown@example.com",
    rank: "Intermediate",
    avatar: userAvatars[5],
    totalWins: 50,
    winRate: 65,
    experience: 1500,
    currentStreak: 2,
    bestRank: 8,
  },
  {
    id: 6,
    userName: "Diana Prince",
    role: "Member",
    email: "diana.prince@example.com",
    rank: "Elite",
    avatar: userAvatars[6],
    totalWins: 90,
    winRate: 76,
    experience: 2300,
    currentStreak: 6,
    bestRank: 4,
  },
  {
    id: 7,
    userName: "Ethan Hunt",
    role: "Member",
    email: "ethan.hunt@example.com",
    rank: "Legendary",
    avatar: userAvatars[7],
    totalWins: 110,
    winRate: 80,
    experience: 2600,
    currentStreak: 7,
    bestRank: 1,
  },
  {
    id: 8,
    userName: "Fiona Gallagher",
    role: "Member",
    email: "fiona.gallagher@example.com",
    rank: "Veteran",
    avatar: userAvatars[8],
    totalWins: 65,
    winRate: 72,
    experience: 1700,
    currentStreak: 2,
    bestRank: 5,
  },
  {
    id: 9,
    userName: "George Clooney",
    role: "Member",
    email: "george.clooney@example.com",
    rank: "Elite",
    avatar: userAvatars[9],
    totalWins: 95,
    winRate: 79,
    experience: 2200,
    currentStreak: 8,
    bestRank: 3,
  },
  {
    id: 10,
    userName: "Hannah Montana",
    role: "Member",
    email: "hannah.montana@example.com",
    rank: "Rookie",
    avatar: userAvatars[10],
    totalWins: 20,
    winRate: 50,
    experience: 400,
    currentStreak: 0,
    bestRank: 15,
  },
  {
    id: 11,
    userName: "Ian Malcolm",
    role: "Member",
    email: "ian.malcolm@example.com",
    rank: "Intermediate",
    avatar: userAvatars[11],
    totalWins: 45,
    winRate: 67,
    experience: 1300,
    currentStreak: 3,
    bestRank: 9,
  },
  {
    id: 12,
    userName: "Jessica Jones",
    role: "Member",
    email: "jessica.jones@example.com",
    rank: "Novice",
    avatar: userAvatars[12],
    totalWins: 15,
    winRate: 48,
    experience: 350,
    currentStreak: 1,
    bestRank: 14,
  },
  {
    id: 13,
    userName: "Kevin Hart",
    role: "Member",
    email: "kevin.hart@example.com",
    rank: "Veteran",
    avatar: userAvatars[13],
    totalWins: 55,
    winRate: 70,
    experience: 1600,
    currentStreak: 4,
    bestRank: 7,
  },
  {
    id: 14,
    userName: "Laura Croft",
    role: "Member",
    email: "laura.croft@example.com",
    rank: "Elite",
    avatar: userAvatars[14],
    totalWins: 85,
    winRate: 75,
    experience: 2100,
    currentStreak: 5,
    bestRank: 2,
  },
  {
    id: 15,
    userName: "Michael Scott",
    role: "Member",
    email: "michael.scott@example.com",
    rank: "Legendary",
    avatar: userAvatars[15],
    totalWins: 105,
    winRate: 82,
    experience: 2500,
    currentStreak: 6,
    bestRank: 1,
  },
  {
    id: 16,
    userName: "Nina Simone",
    role: "Member",
    email: "nina.simone@example.com",
    rank: "Rookie",
    avatar: userAvatars[16],
    totalWins: 10,
    winRate: 40,
    experience: 200,
    currentStreak: 0,
    bestRank: 16,
  },
];
