import { teamAvatars } from "./teamAvatars";

export const mockTeams = [
  {
    id: '0',
    name: 'Phoenix Knights',
    avatar: teamAvatars[0],
    rank: 1,
    members: 6,
    maxMembers: 8,
    winRate: 87,
    totalMatches: 234,
    currentStreak: 12,
    totalWins: 125,
    status: 'online',
    location: 'North America',
    lastActive: '2 min ago',
    description: 'Elite team specializing in strategic gameplay and tournament dominance.',
    specialties: ['Strategy', 'Tournaments', 'Team Coordination'],
    achievements: ['Championship Winners', 'Perfect Season', 'Elite Status'],
    challengeStatus: 'none'
  },
  {
    id: '1',
    name: 'Dragon Slayers',
    avatar: teamAvatars[1],
    rank: 2,
    members: 5,
    maxMembers: 6,
    winRate: 82,
    totalMatches: 189,
    currentStreak: 8,
    totalWins: 110,
    status: 'in-match',
    location: 'Europe',
    lastActive: '15 min ago',
    description: 'Aggressive playstyle with focus on quick victories and high-risk strategies.',
    specialties: ['Aggressive', 'Quick Matches', 'Risk Management'],
    achievements: ['Speed Champions', 'Risk Takers', 'Elite Status'],
    challengeStatus: 'none'
  },
  {
    id: '2',
    name: 'Shadow Assassins',
    avatar: teamAvatars[2],
    rank: 3,
    members: 4,
    maxMembers: 5,
    winRate: 75,
    totalMatches: 150,
    currentStreak: 5,
    totalWins: 120,
    status: 'offline',
    location: 'Asia',
    lastActive: '1 hour ago',
    description: 'Masters of stealth and precision, excelling in ambush tactics.',
    specialties: ['Stealth', 'Precision', 'Ambush'],
    achievements: ['Stealth Masters', 'Precision Experts'],
    challengeStatus: 'none'
  },
  {
    id: '3',
    name: 'Iron Wolves',
    avatar: teamAvatars[3],
    rank: 4,
    members: 7,
    maxMembers: 10,
    winRate: 80,
    totalMatches: 200,
    currentStreak: 10,
    totalWins: 130,
    status: 'online',
    location: 'North America',
    lastActive: '5 min ago',
    description: 'A formidable team known for their resilience and teamwork.',
    specialties: ['Teamwork', 'Resilience', 'Defensive Strategies'],
    achievements: ['Team of the Year', 'Resilience Award'],
    challengeStatus: 'none'
  },
  {
    id: '4',
    name: 'Frost Giants',
    avatar: teamAvatars[4],
    rank: 5,
    members: 6,
    maxMembers: 8,
    winRate: 78,
    totalMatches: 175,
    currentStreak: 3,
    totalWins: 140,
    status: 'in-match',
    location: 'Europe',
    lastActive: '10 min ago',
    description: 'Cold-blooded strategists who excel in long-term planning.',
    specialties: ['Long-term Planning', 'Strategic Defense'],
    achievements: ['Strategic Thinkers', 'Ice Cold Champions'],
    challengeStatus: 'none'
  },
  {
    id: '5',
    name: 'Thunder Hawks',
    avatar: teamAvatars[5],
    rank: 6,
    members: 5,
    maxMembers: 6,
    winRate: 85,
    totalMatches: 160,
    currentStreak: 7,
    totalWins: 150,
    status: 'online',
    location: 'South America',
    lastActive: '20 min ago',
    description: 'Fast and agile, they strike hard and fast before the opponent can react.',
    specialties: ['Speed', 'Agility', 'Quick Strikes'],
    achievements: ['Speed Demons', 'Quick Strike Champions'],
    challengeStatus: 'none'
  },
  {
    id: '6',
    name: 'Mystic Guardians',
    avatar: teamAvatars[6],
    rank: 7,
    members: 6,
    maxMembers: 8,
    winRate: 90,
    totalMatches: 220,
    currentStreak: 15,
    totalWins: 160,
    status: 'online',
    location: 'Asia',
    lastActive: '1 min ago',
    description: 'Guardians of the realm, known for their magical strategies and teamwork.',
    specialties: ['Magic', 'Team Coordination', 'Defense'],
    achievements: ['Guardians of the Realm', 'Magic Masters'],
    challengeStatus: 'none'
  },
  {
    id: '7',
    name: 'Valkyrie Squad',
    avatar: teamAvatars[7],
    rank: 8,
    members: 5,
    maxMembers: 6,
    winRate: 76,
    totalMatches: 140,
    currentStreak: 4,
    totalWins: 170,
    status: 'offline',
    location: 'Australia',
    lastActive: '30 min ago',
    description: 'Fearless warriors ready to conquer any challenge that comes their way.',
    specialties: ['Fearlessness', 'Combat Skills'],
    achievements: ['Warriors of the Year', 'Fearless Fighters'],
    challengeStatus: 'none'
  }
];
